use db000;
describe product;
truncate client;
truncate category;
select * from product;
select * from category;
describe category;
show tables;
select * from next_id;
alter table client modify column id_doc_number VARCHAR(30) not null;
update client set phone = "";
